services:
  - type: web
    name: cardioxai
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn cardioxai.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.11"
